steps:
  - label: ":node: Install and Test"
    commands:
      - echo "--- Installing dependencies"
      - npm install
      - echo "--- Running the app in the background"
      - PORT=3333 node index.js &
      - echo "--- Waiting for app to be ready"
      - sleep 5
      - echo "--- Running tests"
      - npm test
