steps:
  - label: ":node: Dummy check"
    commands:
      - echo "--- Installing dependencies"
      - npm install
      - echo "--- Start and check app"
      - PORT=3100 node index.js &
      - sleep 5
      - curl -f http://localhost:3100/
