steps:
  - label: ":node: Install and Run"
    commands:
      - echo "--- Cleaning old modules"
      - rm -rf node_modules
      - echo "--- Installing dependencies"
      - npm install
      - echo "--- Starting app"
      - node index.js
