steps:
  - label: ":node: Run Node.js App"
    commands:
      - echo "--- Installing dependencies"
      - npm install
      - echo "--- Pick a random free port"
      - export PORT=$((3100 + RANDOM % 1000))
      - echo "Using PORT=$PORT"
      - echo "--- Running the app"
      - node index.js
