steps:
  - label: ":node: Install and Test"
    commands:
      - echo "--- Installing dependencies"
      - npm install
      - echo "--- Running the app in the background on random port"
      - PORT=0 node index.js &
      - echo "--- Wait for app to start"
      - sleep 5
      - echo "--- Running test"
      - npm test
